name: resourcehacker
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: resourcehacker is a free resource extraction utility and resource compiler.
description: |
 resourcehacker has been designed to be the complete resource editing tool & compiling, viewing, decompiling and recompiling resources for both 32bit and 64bit Windows executables. resourcehacker can open any type of Windows executable (*.exe; *.dll; *.scr; *.mui etc) so that individual resources can be added modified or deleted within these files. resourcehacker can create and compile resource script files (*.rc), and edit resource files (*.res) too.

confinement: strict
grade: stable
architectures:
  - build-on: amd64
    run-on: [amd64, i386]

plugs:
  wine-platform-plug:
    content: wine-base-stable
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-i386

apps:
  resourcehacker:
    command: resourcehacker
    desktop: usr/share/applications/resourcehacker.desktop
    plugs: [ wayland, x11, opengl, home, desktop, desktop-legacy, hardware-observe, process-control, cups-control, removable-media, wine-platform-plug ]

parts:
  resourcehacker:
    plugin: nil
    source: ./scripts
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget http://www.angusj.com/resourcehacker/ -q -S -O - 2>&1 | grep Version | awk '{print $2}' | sed 's|</strong><br>||;2d')
      echo $ver > $SNAPCRAFT_STAGE/version
      ./dl_rh
    stage:
      - bin
      - usr
      - wine-platform
    build-packages: [wget, p7zip-full]
